FROM node:20-alpine

ENV CI=true
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund
COPY public ./public
COPY src ./src

ENV GENERATE_SOURCEMAP=false \
    NODE_OPTIONS=--max-old-space-size=1024
RUN npm test -- --watchAll=false --runInBand
RUN npm run build
